#!/usr/bin/env bash
set -eux
cd $(dirname $0)

source db.properties


PSQL="/opt/homebrew/opt/libpq/bin/psql --username=${DB_USER} -d postgres -h ${DB_SERVER_HOST} -w"

PSQL_TPCE="/opt/homebrew/opt/libpq/bin/psql --username=tpce -q -h ${DB_SERVER_HOST} -p 5432 -d tpce -v ON_ERROR_STOP=1 -w"

export DATA_DIR=/Users/lneves/tmp/tpc-e-tool/flat_out


function drop_db {
echo "drop tpce database"
$PSQL -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE datname = 'tpce' AND pid <> pg_backend_pid();"
$PSQL -c "DROP DATABASE IF EXISTS tpce;"
$PSQL -c "DROP TABLESPACE IF EXISTS tblsp_tpce;"
$PSQL -c "DROP ROLE IF EXISTS tpce;"

}

function create_db {
drop_db
echo "create tpce database"
$PSQL -c "CREATE ROLE tpce WITH LOGIN PASSWORD '${TPCE_PASSWORD}';"
$PSQL -c "CREATE TABLESPACE tblsp_tpce OWNER tpce LOCATION '/pg_tblsp_data/';"
$PSQL -c "CREATE DATABASE tpce WITH OWNER=tpce TABLESPACE=tblsp_tpce;"
}


function load_data {
echo "load table data"
$PSQL_TPCE -a -c "\copy account_permission FROM '${DATA_DIR}/AccountPermission.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy customer FROM '${DATA_DIR}/Customer.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy customer_account FROM '${DATA_DIR}/CustomerAccount.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy customer_taxrate FROM '${DATA_DIR}/CustomerTaxrate.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy holding FROM '${DATA_DIR}/Holding.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy holding_history FROM '${DATA_DIR}/HoldingHistory.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy holding_summary FROM '${DATA_DIR}/HoldingSummary.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy watch_item FROM '${DATA_DIR}/WatchItem.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy watch_list FROM '${DATA_DIR}/WatchList.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy broker FROM '${DATA_DIR}/Broker.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy cash_transaction FROM '${DATA_DIR}/CashTransaction.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy charge FROM '${DATA_DIR}/Charge.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy commission_rate FROM '${DATA_DIR}/CommissionRate.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy settlement FROM '${DATA_DIR}/Settlement.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy trade FROM '${DATA_DIR}/Trade.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy trade_history FROM '${DATA_DIR}/TradeHistory.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy trade_type FROM '${DATA_DIR}/TradeType.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy company FROM '${DATA_DIR}/Company.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy company_competitor FROM '${DATA_DIR}/CompanyCompetitor.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy daily_market FROM '${DATA_DIR}/DailyMarket.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy exchange FROM '${DATA_DIR}/Exchange.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy financial FROM '${DATA_DIR}/Financial.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy industry FROM '${DATA_DIR}/Industry.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy last_trade FROM '${DATA_DIR}/LastTrade.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy news_item FROM '${DATA_DIR}/NewsItem.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy news_xref FROM '${DATA_DIR}/NewsXRef.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy sector FROM '${DATA_DIR}/Sector.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy security FROM '${DATA_DIR}/Security.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy address FROM '${DATA_DIR}/Address.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy status_type FROM '${DATA_DIR}/StatusType.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy taxrate FROM '${DATA_DIR}/TaxRate.txt' DELIMITER '|'"
$PSQL_TPCE -a -c "\copy zip_code FROM '${DATA_DIR}/ZipCode.txt' DELIMITER '|'"
}


begin=$(date +%s)

export PGPASSWORD=${DB_PASSWORD}
time create_db


export PGPASSWORD=${TPCE_PASSWORD}
time $PSQL_TPCE -a -f ./1_create_table.sql

time load_data
time $PSQL_TPCE -a -f ./3_create_keys.sql
time $PSQL_TPCE -a -f ./4_create_index.sql
time $PSQL_TPCE -a -f ./5_create_fk.sql
time $PSQL_TPCE -a -f ./6_create_sequence.sql
time $PSQL_TPCE -a -f ./7_analyze_table.sql

end=$(date +%s)
elapsed=$((end-begin))
echo "import took ${elapsed} seconds"
